config/routes.rb
Rails.application.routes.draw do

  root "auctions#index"

  resources :auctions do
    resources :bids
    resources :publishings, only: [:create]
  end

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than: 0}

  belongs_to :user

  has_many :bids, dependent: :destroy
  has_many :biddings_users, through: :bids, source: :user

  include AASM


  aasm whiny_transitions: false do
    state :published, initial: true
    state :reserve_met
    state :won
    state :canceled
    state :reserve_not_met


    event :reserve do
      transitions from: :published, to: :reserve_met
    end

    event :win do
      transitions from: :reserve_met, to: :won
    end

    event :close do
      transitions from: [:published, :reserve_not_met], to: :canceled
    end

  end

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  validates :price, presence: true



end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :auctions, dependent: :destroy

  has_many :bids, dependent: :destroy
  has_many :bidded_auctions, through: :bids, source: :auction

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user
    unless user_signed_in?
      redirect_to new_session_path, alert: "Please sign in!"
    end
  end

  def current_user
    @current_user ||= User.find_by_id session[:user_id] if session[:user_id]
  end

  helper_method :current_user

  def user_signed_in?
   current_user.present?
  end

  helper_method :user_signed_in?




end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]

  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    auction_params = params.require(:auction).permit([:title, :price, :details, :end_date])
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to @auction, notice: "Auction create successefuly!"
    else
      render :new, alert: "Error"
    end
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    @current_price = @auction.bids.maximum(:price)
  end


end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user

  def new
    @bid = Bid.new
  end

  def create
    @auction = Auction.find params[:auction_id]
    @current_price = @auction.bids.maximum(:price)
    bid_params = params.require(:bid).permit(:price)
    @bid = Bid.new bid_params
    @bid.user = current_user
    @bid.auction = @auction
    respond_to do |format|
      if current_user != @auction.user
        if (@auction.bids.first == nil) || (@auction.bids.maximum(:price) < @bid.price)
          @bid.save
          format.html {redirect_to @auction, notice: "Bid created!"}
          format.js {render :create_success}
        else
          format.html {render "auction/show"}
          format.js {render js: "alert('failure');"}
        end
      else
        redirect_to auction_path(@auction), alert: "You cant Bid you on Auction!"
      end
    end
  end

end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController

  before_action :authenticate_user

  def create
    auction = Auction.find params[:auction_id]
    if auction.reserve
      auction.save
      redirect_to auction, notice: "Auction Reserved"
    else
      redirect_to auction, alert: "Cant' reserve"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
   user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "logged in"
    else
    flash[:alert] = "wrong credentials"
    render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                              :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper

  def label_class(state)
    case state
    when "published"
      "label-default"
    when "reserve_met"
      "label-primary"
    when "won"
      "label-success"
    when "reserve_not_met"
      "label-danger"
    when "canceled"
      "label-warning"
    end
  end


end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
<h2 class="text-center">Auctions</h2>

<% @auctions.each do |auc| %>
  <div class="well">
    <div class="">
    <h1> <%= link_to auc.title, auction_path(auc) %> </h1>
    </div>
    <div class="">
      <%= auc.details %>
    </div>
    <div class="">
      <h5>End date: <%= auc.end_date %></h5>
    </div>
  </div>
<% end %>

app/views/auctions/new.html.erb
<h2>Create a new Auction</h2>

<%= simple_form_for @auction do |f| %>

<%= f.input :title %>
<%= f.input :price %>
<%= f.input :end_date %>
<%= f.input :details, hint: "Puts details about your auction"%>
<%= f.submit class: "btn btn-success" %>

<% end %>

app/views/auctions/show.html.erb
<h2 class="text-center">Auction</h2>
<div class="well">
  <div class="">
    <h1><%= @auction.title %></h1>
  </div>
  <div class="">
    <h5>Created by: <%= @auction.user.first_name.capitalize %></h5>
  </div>
  <div class="">
    <p>Details: <%= @auction.details %></p>
  </div>
  <div class="">
    <h5>End date: <%= @auction.end_date %></h5>
  </div>
  <div class="">
    <h3>Current Price: $ <%= @current_price %></h3>
  </div>
  <p><span class="label <%=  label_class(@auction.aasm_state) %>">
    <%= @auction.aasm_state.capitalize %></span> </p>

  <% if @current_price && @current_price > @auction.price %>
    <% if @auction.published? %>
      <%= link_to "Reserve", auction_publishings_path(@auction), method: :post,
                                                        class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

<!-- --------- bid form ----------- -->

<% if @auction.published? %>

  <div class="form-group">
    <%= simple_form_for [@auction, @bid], remote: true do |f| %>
    <%= f.input :price %>
    <%= f.submit "Create a Bid", class: "btn btn-primary btn-sm", data: {disable_with: "Saving..."} %>
    <% end %>

  </div>


  <!-- bids -->
  <div  id="bid">
      <% @auction.bids.each do |bid| %>

        <%= render "/bids/bid", bid: bid %>

      <% end %>
  </div>

<% end %>

app/views/bids/_bid.html.erb
<div id="<%= dom_id(bid) %>">
  <div class="well">
    $<%= bid.price %> - Bidded by: <%= bid.user.full_name.capitalize %>
  </div>

</div>

app/views/bids/create_success.js.erb
$("#bid").prepend("<%= j render '/bids/bid', bid: @bid %>");
$("#bid_price").val("");

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biddr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="nav navbar navbar-default">
  <div class="container">


    <% if user_signed_in? %>
    <%= link_to current_user.first_name, current_user %> |
    <%= link_to "Logout", sessions_path, method: :delete%> |
    <% else %>
    <%= link_to "Login", new_session_path %> |
    <%= link_to "Sign up", new_user_path %> |
    <% end %>
    <%= link_to "Create a Auction", new_auction_path %> |
    <%= link_to "All Auctions", root_path %>


  </div>
</nav>

<div class="col-md-2"></div>
<div class="col-md-8">
  <%= render "/layouts/flash_messages" %>
  <%= yield %>
</div>
<div class="col-md-2"></div>


</body>
</html>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1 class="text-center"> <%= current_user.full_name.capitalize %></h1>

<div class="well text-center">
  <% @user.bids.each do |bid| %>
  <h3> Auction: <%= bid.auction.title %></h3>
  <h3> Bid value: <%= bid.auction.price %></h3>
  <hr>
  <% end %>
</div>